port:  5000
markdown: kramdown
name: Illinois Re-Entry Resources
title: Illinois Re-Entry Resources
description: ""
encoding: utf-8
url: "http://map.reentrycolab.org"
baseurl: ""
guide_link: "https://www.dropbox.com/s/ijthbhpnx05oehq/Re-entry%20Guide%202016_v5_nomarks.pdf?dl=0"
timezone: America/Chicago
