port:  5000
markdown: kramdown
name: Illinois Re-Entry Resources
title: Illinois Re-Entry Resources
description: ""
encoding: utf-8
url: "https://reentryillinois.net"
baseurl: ""
guide_link: "https://www.dropbox.com/s/ts95t6axw1v9a82/Re-entry%20Guide%202017_Web.pdf?dl=1"
timezone: America/Chicago
