port:  5000
markdown: kramdown
name: Illinois Re-Entry Resources
title: Illinois Re-Entry Resources
description: ""
encoding: utf-8
url: "https://pjsier.github.io"
baseurl: "/probation-resources-map"
timezone: America/Chicago
