port: 5000
markdown: kramdown
name: Illinois Re-Entry Resources
title: Illinois Re-Entry Resources
description: ""
encoding: utf-8
url: "https://reentryillinois.net"
baseurl: ""
guide_links:
  - title: COVID-19 Reentry Guide
    links:
      - url: http://www.educationjustice.net/home/wp-content/uploads/2020/05/EJP-COVID-19-Reentry-Guide_May-2020_digital_1.pdf
        label: English
      - url: http://www.educationjustice.net/home/wp-content/uploads/2020/05/COVID-19-Pamphlet-Spanish-1.pdf
        label: Español
  - title: Returning Home Reentry Guide
    links:
      - url: https://drive.google.com/file/d/1K5f1fikdYloaZaxfyZvED6Sxd_m3pzrL/view
        label: English
      - url: http://www.educationjustice.net/home/wp-content/uploads/2020/10/Regresando-a-casa-2020.pdf
        label: Español
  - title: Mapping Your Future
    links:
      - url: http://www.educationjustice.net/home/wp-content/uploads/2020/10/Mapping-Your-Future-08.18-interactive.pdf
        label: English
timezone: America/Chicago
